
import java.util.Arrays;
import java.util.Optional;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Family
 */

public class AirLineTickets extends javax.swing.JFrame {

    /**
     * Creates new form AirLineTickets
     */
    
    TicketParser check = new TicketParser();
    Boolean seatsArray [] = new Boolean[9] ;
    int num = 0;
    int firstClsSts = 0;
    int scndClsSts  = 5;
    String varFirstNM;
    String varLastNM;
    String varCity;
    String varState;
    
         
    public AirLineTickets() 
    {
      
        initComponents();
        Arrays.fill(seatsArray, Boolean.FALSE);
        check.setPerson(1);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        firstNameTxtFld = new javax.swing.JTextField();
        lastNameTxtFld = new javax.swing.JTextField();
        stateTxtFld = new javax.swing.JTextField();
        cityTxtFld = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        firstClass = new javax.swing.JCheckBox();
        secondClass = new javax.swing.JCheckBox();
        firstName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(null);

        jPanel1.setLayout(null);

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrder);
        btnOrder.setBounds(190, 220, 67, 32);

        firstNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtFldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameTxtFld);
        firstNameTxtFld.setBounds(390, 220, 100, 30);
        jPanel1.add(lastNameTxtFld);
        lastNameTxtFld.setBounds(390, 260, 100, 30);
        jPanel1.add(stateTxtFld);
        stateTxtFld.setBounds(390, 310, 100, 30);
        jPanel1.add(cityTxtFld);
        cityTxtFld.setBounds(390, 360, 100, 30);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(540, 360, 77, 32);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(540, 310, 80, 32);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Airline Tickets");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 80, 180, 40);

        firstClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        firstClass.setText("First Class");
        firstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstClassActionPerformed(evt);
            }
        });
        jPanel1.add(firstClass);
        firstClass.setBounds(540, 220, 110, 24);

        secondClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        secondClass.setText("Economy");
        secondClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondClassActionPerformed(evt);
            }
        });
        jPanel1.add(secondClass);
        secondClass.setBounds(540, 250, 110, 24);

        firstName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        firstName.setText("First Name:");
        jPanel1.add(firstName);
        firstName.setBounds(280, 230, 90, 19);

        lastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lastName.setText("Last Name:");
        jPanel1.add(lastName);
        lastName.setBounds(280, 270, 80, 20);

        city.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        city.setText("City:");
        jPanel1.add(city);
        city.setBounds(330, 370, 30, 19);

        state.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        state.setText("State:");
        jPanel1.add(state);
        state.setBounds(320, 320, 40, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outDoor.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 470);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
     
 
    TicketParser ch = new TicketParser();
    

    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            firstClass.setSelected(false);
            secondClass.setSelected(false);
            firstNameTxtFld.setText("");
            lastNameTxtFld.setText("");
            cityTxtFld.setText("");
            stateTxtFld.setText("");
            
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void secondClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondClassActionPerformed
        // TODO add your handling code here:
        if(secondClass.isSelected())
        {
            firstClass.setSelected(false);
        } 
    }//GEN-LAST:event_secondClassActionPerformed

    private void firstClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstClassActionPerformed
       if(firstClass.isSelected())
        {
            secondClass.setSelected(false);
        }        // TODO add your handling code here:
     
    }//GEN-LAST:event_firstClassActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
                  
                 check.setFirstName(varFirstNM = firstNameTxtFld.getText());
                 check.setLastName(varLastNM   = lastNameTxtFld.getText());
                 check.setCity(varCity = cityTxtFld.getText());
                 check.setState(varState = stateTxtFld.getText());
        
        if(firstClass.isSelected())
        {                   
            if(firstClsSts >= 5) 
            {
                 firstClsSts = 5; 
                 check.SectionFull();
                 return;
            }
            check.SeatChecker(firstClsSts);
            firstClsSts++;
  
        }        // TODO add your handling code here:
       
        if(secondClass.isSelected())
        {
           if(scndClsSts >= 10 ) 
            {
                scndClsSts = 10; 
                check.SectionFull();
                return;
            }
            check.SeatChecker(scndClsSts);
            scndClsSts++;
        } 
      
    }//GEN-LAST:event_btnOrderActionPerformed

    private void firstNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirLineTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirLineTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirLineTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirLineTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirLineTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityTxtFld;
    private javax.swing.JCheckBox firstClass;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameTxtFld;
    private javax.swing.JCheckBox secondClass;
    private javax.swing.JLabel state;
    private javax.swing.JTextField stateTxtFld;
    // End of variables declaration//GEN-END:variables
}
